// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VComposedMultiIOTester.cpp"
#include "VComposedMultiIOTester__Trace.cpp"
#include "VComposedMultiIOTester__Slow.cpp"
#include "VComposedMultiIOTester__Syms.cpp"
#include "VComposedMultiIOTester__Trace__Slow.cpp"
