// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VAsTypeOfClockTester.cpp"
#include "VAsTypeOfClockTester__Trace.cpp"
#include "VAsTypeOfClockTester__Slow.cpp"
#include "VAsTypeOfClockTester__Syms.cpp"
#include "VAsTypeOfClockTester__Trace__Slow.cpp"
